config/routes.rb
Rails.application.routes.draw do
  resources :payment_methods
  resources :physicals
  resources :digitals
  resources :products

  resources :purchase_orders do
      post 'add_product/:product_id', to: 'purchase_orders#add_product'
  end
 end

app/models/digital.rb
class Digital < ApplicationRecord
  has_one_attached :image
  has_many :products, as: :itemizable
end

app/controllers/digitals_controller.rb
class DigitalsController < ApplicationController
  before_action :set_digital, only: [:show, :edit, :update, :destroy]

  # GET /digitals
  # GET /digitals.json
  def index
    @digitals = Digital.all
  end

  # GET /digitals/1
  # GET /digitals/1.json
  def show
  end

  # GET /digitals/new
  def new
    @digital = Digital.new
  end

  # GET /digitals/1/edit
  def edit
  end

  # POST /digitals
  # POST /digitals.json
  def create
    @digital = Digital.new(digital_params)

    respond_to do |format|
      if @digital.save
        format.html { redirect_to @digital, notice: 'Digital was successfully created.' }
        format.json { render :show, status: :created, location: @digital }
      else
        format.html { render :new }
        format.json { render json: @digital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /digitals/1
  # PATCH/PUT /digitals/1.json
  def update
    respond_to do |format|
      if @digital.update(digital_params)
        format.html { redirect_to @digital, notice: 'Digital was successfully updated.' }
        format.json { render :show, status: :ok, location: @digital }
      else
        format.html { render :edit }
        format.json { render json: @digital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /digitals/1
  # DELETE /digitals/1.json
  def destroy
    @digital.destroy
    respond_to do |format|
      format.html { redirect_to digitals_url, notice: 'Digital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_digital
      @digital = Digital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def digital_params
      params.require(:digital).permit(:name, :image, :stock)
    end
end

app/helpers/digitals_helper.rb
module DigitalsHelper
end

app/views/digitals/_form.html.erb
<%= form_with(model: digital, local: true) do |form| %>
  <% if digital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(digital.errors.count, "error") %> prohibited this digital from being saved:</h2>

      <ul>
      <% digital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
	<%= form.label :image %>
	<%= form.file_field :image %>
  </div>
  
  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/digitals/edit.html.erb
<h1>Editing Digital</h1>

<%= render 'form', digital: @digital %>

<%= link_to 'Show', @digital %> |
<%= link_to 'Back', digitals_path %>

app/views/digitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Digitals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @digitals.each do |digital| %>
      <tr>
        <td><%= digital.name %></td>
        <td><%= image_tag digital.image.variant(resize: "50x50").processed %></td>
        <td><%= digital.stock %></td>
        <td><%= link_to 'Show', digital %></td>
        <td><%= link_to 'Edit', edit_digital_path(digital) %></td>
        <td><%= link_to 'Destroy', digital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Digital', new_digital_path %>

app/views/digitals/new.html.erb
<h1>New Digital</h1>

<%= render 'form', digital: @digital %>

<%= link_to 'Back', digitals_path %>

app/views/digitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @digital.name %>
</p>

<%= link_to 'Edit', edit_digital_path(@digital) %> |
<%= link_to 'Back', digitals_path %>