config/routes.rb
Rails.application.routes.draw do
  resources :payment_methods
  resources :physicals
  resources :digitals
  resources :products

  resources :purchase_orders do
      post 'add_product/:product_id', to: 'purchase_orders#add_product'
  end
 end

app/models/physical.rb
class Physical < ApplicationRecord
  has_many_attached :images
  has_many :products, as: :itemizable
end

app/controllers/physicals_controller.rb
class PhysicalsController < ApplicationController
  before_action :set_physical, only: [:show, :edit, :update, :destroy]

  # GET /physicals
  # GET /physicals.json
  def index
    @physicals = Physical.with_attached_images.all
  end

  # GET /physicals/1
  # GET /physicals/1.json
  def show
  end

  # GET /physicals/new
  def new
    @physical = Physical.new
  end

  # GET /physicals/1/edit
  def edit
  end

  # POST /physicals
  # POST /physicals.json
  def create
    @physical = Physical.new(physical_params)

    respond_to do |format|
      if @physical.save
        format.html { redirect_to @physical, notice: 'Physical was successfully created.' }
        format.json { render :show, status: :created, location: @physical }
      else
        format.html { render :new }
        format.json { render json: @physical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicals/1
  # PATCH/PUT /physicals/1.json
  def update
    respond_to do |format|
      if @physical.update(physical_params)
        format.html { redirect_to @physical, notice: 'Physical was successfully updated.' }
        format.json { render :show, status: :ok, location: @physical }
      else
        format.html { render :edit }
        format.json { render json: @physical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicals/1
  # DELETE /physicals/1.json
  def destroy
    @physical.destroy
    respond_to do |format|
      format.html { redirect_to physicals_url, notice: 'Physical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical
      @physical = Physical.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physical_params
      params.require(:physical).permit(:name, :stock, images: [])
    end
end

app/helpers/physicals_helper.rb
module PhysicalsHelper
end

app/views/physicals/_form.html.erb
<%= form_with(model: physical, local: true) do |form| %>
  <% if physical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physical.errors.count, "error") %> prohibited this physical from being saved:</h2>

      <ul>
      <% physical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
	<%= form.label :images %>
	<%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/physicals/edit.html.erb
<h1>Editing Physical</h1>

<%= render 'form', physical: @physical %>

<%= link_to 'Show', @physical %> |
<%= link_to 'Back', physicals_path %>

app/views/physicals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physicals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stock</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicals.each do |physical| %>
      <tr>
        <td><%= physical.name %></td>
        <td><%= physical.stock %></td>
        <%= image_tag physical.images.last.variant(resize: "50x50").processed %>
        <td><%= link_to 'Show', physical %></td>
        <td><%= link_to 'Edit', edit_physical_path(physical) %></td>
        <td><%= link_to 'Destroy', physical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physical', new_physical_path %>

app/views/physicals/new.html.erb
<h1>New Physical</h1>

<%= render 'form', physical: @physical %>

<%= link_to 'Back', physicals_path %>

app/views/physicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physical.name %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @physical.stock %>
</p>

<%= link_to 'Edit', edit_physical_path(@physical) %> |
<%= link_to 'Back', physicals_path %>